sample/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
from sample.view import home,about_us,feedback,demo,register
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', home),
    # url(r'^blog/', include('blog.urls')),
#     url(r'^', home),
    url(r'^admin/$', include(admin.site.urls)),
    url(r'^home/$', home),
    url(r'^about_us/$', about_us),
    url(r'^feedback/$', feedback),
    url(r'^register/$', register),
    url(r'^demo/$', demo),
    
)

sample/models.py
from django.db import models

class registration_model(models.Model):
    member_code = models.CharField(max_length=1000)
    f_name = models.CharField(max_length=70)
    m_name = models.CharField(max_length=70)
    l_name = models.CharField(max_length=70)
    sex = models.CharField(max_length=10)
    age = models.IntegerField()
    status = models.CharField(max_length=10)
    education = models.CharField(max_length=70)
    present_address = models.CharField(max_length=500)
    present_address_pin = models.IntegerField()
    permonant_address = models.CharField(max_length=500)
    permonant_address_pin = models.IntegerField()
    pan_no = models.CharField(max_length=70)
    passport_no = models.CharField(max_length=70)
    mobile_no = models.CharField(max_length=70)
    landline_no = models.CharField(max_length=70)
    e_mail = models.EmailField()
    alternate_email = models.EmailField()
    city = models.CharField(max_length=70)
    pin = models.IntegerField()
    state = models.CharField(max_length=70)
    country = models.CharField(max_length=70)

class feedback_model(models.Model):
    f_name = models.CharField(max_length=70)
    l_name = models.CharField(max_length=70)
    e_mail = models.EmailField()
    mobile_no = models.CharField(max_length=70)
    comments = models.CharField(max_length=1000)

templates/sample/about_us.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Template &middot; Bootstrap</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    {% load static from staticfiles %}
    <link href="{% static "bootstrap/css/bootstrap.min.css" %}" rel="stylesheet">
    <style type="text/css">
      body {
        padding-top: 20px;
        padding-bottom: 40px;
      }

      /* Custom container */
      .container-narrow {
        margin: 0 auto;
        max-width: 700px;
      }
      .container-narrow > hr {
        margin: 30px 0;
      }

      /* Main marketing message and sign up button */
      .jumbotron {
        margin: 60px 0;
        text-align: center;
      }
      .jumbotron h1 {
        font-size: 72px;
        line-height: 1;
      }
      .jumbotron .btn {
        font-size: 21px;
        padding: 14px 24px;
      }

      /* Supporting marketing content */
      .marketing {
        margin: 60px 0;
      }
      .marketing p + h4 {
        margin-top: 28px;
      }
    </style>
	<link href="{% static "css/style.css" %}" rel="stylesheet">
    <link href="{% static "bootstrap/css/bootstrap-responsive.css" %}" rel="stylesheet">
    
    <!-- Fav and touch icons -->
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="../assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="../assets/ico/apple-touch-icon-114-precomposed.png">
      <link rel="apple-touch-icon-precomposed" sizes="72x72" href="../assets/ico/apple-touch-icon-72-precomposed.png">
                    <link rel="apple-touch-icon-precomposed" href="../assets/ico/apple-touch-icon-57-precomposed.png">
                                   <link rel="shortcut icon" href="../assets/ico/favicon.png">
  </head>

  <body>

    <div class="container">

      <div class="masthead">
        <ul class="nav nav-pills pull-right">
          <li><a href="/home">Home</a></li>
          <li class="active"><a href="/about_us">About</a></li>
          <li><a href="/register">Register</a></li>
          <li><a href="/feedback">Feedback</a></li>
        </ul>
        <h3 class="muted company_name">Shri Swami Samarth Multitrade Pvt. Ltd.</h3>
      </div>

      <hr>

      <div class="jumbotron container">
        <h3>About Us</h3>
        <div class="col-lg-6">
          <h4>Contact <b></h4>
          <p>E mail: smpl2k14@gmail.com<br>
                      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;smplbiz@gmail.com<br>
            Contact person: Sachin Honde<br>( +91-72766851376 )<br>

          </p>
        </div>
        <div class="col-lg-6">
          <h4>Address</h4>
           <p>Branch Office:A/P-Ghodegaon , Nagar ,<br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Aurangabad road,<br> Taluka-Nevasa, Dist- Amhadnagar </p>
        </div>

      </div>

      <hr>

      <div class="row-fluid marketing company_name">
        <div class="col-lg-6">
          <h4>Our Mission</h4>
          <p>We have our own moral ethics on which company stands.
              Shri swami samarth multitrade pvt ltd company stands to provide
              employment for unemployed persons and guide about how to do
              successful business.Shri swami samarth multitrade pvt ltd provides
              opportunity to educated as well as uneducated unemployed persons
              and become supporting pillar for them.

          </p>
        </div>
        <div class="col-lg-6">
          <h4>Our Vision</h4>
           <p>The main objective of the company is to provide employement to
           educated as well as uneducated  needy unemployed persons.</p>
        </div>
      </div>

      <hr>

      <div class="footer">
        <p>&copy; Company 2013</p>
      </div>

    </div> <!-- /container -->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static "bootstrap/js/jquery.js" %}"></script>
    <script src="{% static "bootstrap/js/bootstrap-transition.js" %}"></script>
    <script src="{% static "bootstrap/js/bootstrap-alert.js" %}"></script>
    <script src="{% static "bootstrap/js/bootstrap-modal.js" %}"></script>
    <script src="{% static "bootstrap/js/bootstrap-dropdown.js" %}"></script>
    <script src="{% static "bootstrap/js/bootstrap-scrollspy.js" %}"></script>
    <script src="{% static "bootstrap/js/bootstrap-tab.js" %}"></script>
    <script src="{% static "bootstrap/js/bootstrap-tooltip.js" %}"></script>
    <script src="{% static "bootstrap/js/bootstrap-popover.js" %}"></script>
    <script src="{% static "bootstrap/js/bootstrap-button.js" %}"></script>
    <script src="{% static "bootstrap/js/bootstrap-collapse.js" %}"></script>
    <script src="{% static "bootstrap/js/bootstrap-carousel.js" %}"></script>
    <script src="{% static "bootstrap/js/bootstrap-typeahead.js" %}"></script>

  </body>
</html>

templates/sample/feedback.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Template &middot; Bootstrap</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    {% load static from staticfiles %}
    <link href="{% static "bootstrap/css/bootstrap.min.css" %}" rel="stylesheet">
    <style type="text/css">
      body {
        padding-top: 20px;
        padding-bottom: 40px;
      }

      /* Custom container */
      .container-narrow {
        margin: 0 auto;
        max-width: 700px;
      }
      .container-narrow > hr {
        margin: 30px 0;
      }

      /* Main marketing message and sign up button */
      .jumbotron {
        margin: 60px 0;
        text-align: center;
      }
      .jumbotron h1 {
        font-size: 72px;
        line-height: 1;
      }
      .jumbotron .btn {
        font-size: 21px;
        padding: 14px 24px;
      }

      /* Supporting marketing content */
      .marketing {
        margin: 60px 0;
      }
      .marketing p + h4 {
        margin-top: 28px;
      }
    </style>
	<link href="{% static "css/style.css" %}" rel="stylesheet">
    <link href="{% static "bootstrap/css/bootstrap-responsive.css" %}" rel="stylesheet">
    
    <!-- Fav and touch icons -->
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="../assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="../assets/ico/apple-touch-icon-114-precomposed.png">
      <link rel="apple-touch-icon-precomposed" sizes="72x72" href="../assets/ico/apple-touch-icon-72-precomposed.png">
                    <link rel="apple-touch-icon-precomposed" href="../assets/ico/apple-touch-icon-57-precomposed.png">
                                   <link rel="shortcut icon" href="../assets/ico/favicon.png">
  </head>

  <body>

    <div class="container">

      <div class="masthead">
        <ul class="nav nav-pills pull-right">
          <li><a href="/home">Home</a></li>
          <li><a href="/about_us">About</a></li>
          <li><a href="/register">Register</a></li>
          <li class="active"><a href="/feedback">Feedback</a></li>
        </ul>
        <h3 class="muted company_name">Shri Swami Samarth Multitrade Pvt. Ltd.</h3>
      </div>

      <hr>

      <div class="jumbotron">
{#            {{ form.as_p }}#}
{#            <div>#}
{#                <p><label class="col-sm-2 control-label" for="id_f_name">Your Name:</label> <input class="form-control"  id="id_f_name" maxlength="20" name="f_name" type="text" /></p>\n#}
{#                <p><label class="col-sm-2 control-label" for="id_l_name">Last Name:</label> <input class="form-control"  id="id_l_name" maxlength="20" name="l_name" type="text" /></p>\n#}
{#                <p><label class="col-sm-2 control-label" for="id_e_mail">E mail:</label> <input class="form-control"  id="id_e_mail" name="e_mail" type="email" /></p>\n#}
{#                <p><label class="col-sm-2 control-label" for="id_mobile_no">Mobile no:</label> <input class="form-control"  id="id_mobile_no" name="mobile_no" type="text" /></p>\n#}
{#                <p><label class="col-sm-2 control-label" for="id_comments">Comments:</label> <textarea class="form-control"  cols="40" id="id_comments" name="comments" rows="10">\r\n</textarea></p>#}
{#            </div>#}
            <div class="form_group">
                <form class="form-horizontal" action="/feedback/" method="post">{% csrf_token %}
                  <div class="form-group">
                    <label class="col-sm-2 control-label" for="id_f_name">Your Name:</label>
                    <div class="col-sm-10">
                      <input class="form-control"  id="id_f_name" maxlength="20" name="f_name" type="text" />
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="col-sm-2 control-label" for="id_l_name">Last Name:</label>
                    <div class="col-sm-10">
                      <input class="form-control"  id="id_l_name" maxlength="20" name="l_name" type="text" />
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="col-sm-2 control-label" for="id_e_mail">E mail:</label>
                    <div class="col-sm-10">
                      <input class="form-control"  id="id_e_mail" name="e_mail" type="email" />
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="col-sm-2 control-label" for="id_mobile_no">Mobile no:</label>
                    <div class="col-sm-10">
                      <input class="form-control"  id="id_mobile_no" name="mobile_no" type="text" />
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="col-sm-2 control-label" for="id_comments">Comments:</label>
                    <div class="col-sm-10">
                      <textarea class="form-control"  cols="40" id="id_comments" name="comments" rows="10"></textarea>
                    </div>
                  </div>

                  <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <div class="btn-group">
                          <input type="submit" class="btn btn-large btn-success" value="Submit" />
                          <input type="button" class="btn btn-large btn-warning" value="Clear" />
                          <input type="button" class="btn btn-large btn-success" value="Back" />
                        </div>
                    </div>
                  </div>
                </form>
            </div>
{#            <div class="btn-group">#}
{#                <input type="submit" class="btn btn-large btn-success" value="Submit" />#}
{#                <input type="button" class="btn btn-large btn-warning" value="Clear" />#}
{#                <input type="button" class="btn btn-large btn-success" value="Back" />#}
{#            </div>#}

      </div>

      <hr>

      <div class="row-fluid marketing">
        <div class="span6">
          <h4>Subheading</h4>
          <p>Donec id elit non mi porta gravida at eget metus. Maecenas faucibus mollis interdum.</p>

          <h4>Subheading</h4>
          <p>Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Cras mattis consectetur purus sit amet fermentum.</p>

          <h4>Subheading</h4>
          <p>Maecenas sed diam eget risus varius blandit sit amet non magna.</p>
        </div>

        <div class="span6">
          <h4>Subheading</h4>
          <p>Donec id elit non mi porta gravida at eget metus. Maecenas faucibus mollis interdum.</p>

          <h4>Subheading</h4>
          <p>Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Cras mattis consectetur purus sit amet fermentum.</p>

          <h4>Subheading</h4>
          <p>Maecenas sed diam eget risus varius blandit sit amet non magna.</p>
        </div>
      </div>

      <hr>

      <div class="footer">
        <p>&copy; Company 2013</p>
      </div>

    </div> <!-- /container -->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static "bootstrap/js/jquery.js" %}"></script>
    <script src="{% static "bootstrap/js/bootstrap-transition.js" %}"></script>
    <script src="{% static "bootstrap/js/bootstrap-alert.js" %}"></script>
    <script src="{% static "bootstrap/js/bootstrap-modal.js" %}"></script>
    <script src="{% static "bootstrap/js/bootstrap-dropdown.js" %}"></script>
    <script src="{% static "bootstrap/js/bootstrap-scrollspy.js" %}"></script>
    <script src="{% static "bootstrap/js/bootstrap-tab.js" %}"></script>
    <script src="{% static "bootstrap/js/bootstrap-tooltip.js" %}"></script>
    <script src="{% static "bootstrap/js/bootstrap-popover.js" %}"></script>
    <script src="{% static "bootstrap/js/bootstrap-button.js" %}"></script>
    <script src="{% static "bootstrap/js/bootstrap-collapse.js" %}"></script>
    <script src="{% static "bootstrap/js/bootstrap-carousel.js" %}"></script>
    <script src="{% static "bootstrap/js/bootstrap-typeahead.js" %}"></script>

  </body>
</html>

templates/sample/register.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Template &middot; Bootstrap</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    {% load static from staticfiles %}
    <link href="{% static "bootstrap/css/bootstrap.min.css" %}" rel="stylesheet">
    <style type="text/css">
      body {
        padding-top: 20px;
        padding-bottom: 40px;
      }

      /* Custom container */
      .container-narrow {
        margin: 0 auto;
        max-width: 700px;
      }
      .container-narrow > hr {
        margin: 30px 0;
      }

      /* Main marketing message and sign up button */
      .jumbotron {
        margin: 60px 0;
        text-align: center;
      }
      .jumbotron h1 {
        font-size: 72px;
        line-height: 1;
      }
      .jumbotron .btn {
        font-size: 21px;
        padding: 14px 24px;
      }

      /* Supporting marketing content */
      .marketing {
        margin: 60px 0;
      }
      .marketing p + h4 {
        margin-top: 28px;
      }
    </style>
	<link href="{% static "css/style.css" %}" rel="stylesheet">
    <link href="{% static "bootstrap/css/bootstrap-responsive.css" %}" rel="stylesheet">
    
    <!-- Fav and touch icons -->
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="../assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="../assets/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="../assets/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="../assets/ico/apple-touch-icon-57-precomposed.png">
    <link rel="shortcut icon" href="../assets/ico/favicon.png">
  </head>

  <body>

    <div class="container">

      <div class="masthead">
        <ul class="nav nav-pills pull-right">
          <li><a href="/home">Home</a></li>
          <li><a href="/about_us">About</a></li>
          <li class="active"><a href="/register">Register</a></li>
          <li><a href="/feedback">Feedback</a></li>
        </ul>
        <h3 class="muted company_name">Shri Swami Samarth Multitrade Pvt. Ltd.</h3>
      </div>

      <hr>

      <div class="jumbotron">
{#        <form action="/register/" method="post">{% csrf_token %}#}
{#            {{ form.as_table }}#}
{#            <input type="submit" class="btn btn-large btn-success" value="Submit" />#}
{#        </form>#}

        <form class="form-horizontal" role="form"action="/register/" method="post">{% csrf_token %}
          <div class="form-group">
            <label class="col-sm-2 control-label  for="id_member_code">Member Code:</label>
            <div class="col-sm-3">
              <input class="form-control"   id="id_member_code" name="member_code" type="text" />
            </div>
          </div>
          <div class="form-group">
            <label class="col-sm-2 control-label for="id_f_name">Your Name:</label>
            <div class="col-sm-10">
              <input class="form-control"  id="id_f_name" maxlength="20" name="f_name" type="text" />
            </div>
          </div>
          <div class="form-group">
            <label class="col-sm-2 control-label for="id_m_name">Middle Name:</label>
            <div class="col-sm-10">
              <input class="form-control"  id="id_m_name" maxlength="20" name="m_name" type="text" />
            </div>
          </div>
          <div class="form-group">
            <label class="col-sm-2 control-label for="id_l_name">Last Name:</label>
            <div class="col-sm-10">
              <input class="form-control"  id="id_l_name" maxlength="20" name="l_name" type="text" />
            </div>
          </div>
          <div class="form-group">
            <label class="col-sm-2 control-label for="id_sex">Sex:</label>
            <div class="col-sm-3">
              <select class="form-control"  id="id_sex" name="sex">\n<option value="male">Male</option>\n<option value="female">Female</option>\n</select>
            </div>
          </div>
          <div class="form-group">
            <label class="col-sm-2 control-label for="id_age">Age:</label>
            <div class="col-sm-3">
              <input class="form-control"  id="id_age" max="150" min="12" name="age" type="number" />
            </div>
          </div>
          <div class="form-group">
            <label class="col-sm-2 control-label for="id_status">Status:</label>
            <div class="col-sm-3">
              <select class="form-control"  id="id_status" name="status">\n<option value="married">Married</option>\n<option value="unmarried">Unmarried</option>\n</select>
            </div>
          </div>
          <div class="form-group">
            <label class="col-sm-2 control-label for="id_education">Education:</label>
            <div class="col-sm-10">
              <input class="form-control"  id="id_education" name="education" type="text" />
            </div>
          </div>
          <div class="form-group">
            <label class="col-sm-2 control-label for="id_present_address">Present address:</label>
            <div class="col-sm-10">
             <input class="form-control"  id="id_present_address" name="present_address" type="text" />
            </div>
          </div>
          <div class="form-group">
            <label class="col-sm-2 control-label for="id_present_address_pin">Present address pin:</label>
            <div class="col-sm-3">
              <input class="form-control"  id="id_present_address_pin" name="present_address_pin" type="number" />
            </div>
          </div>
          <div class="form-group">
            <label class="col-sm-2 control-label for="id_permonant_address">Permonant address:</label>
            <div class="col-sm-10">
              <input class="form-control"  id="id_permonant_address" name="permonant_address" type="text" />
            </div>
          </div>
          <div class="form-group">
            <label class="col-sm-2 control-label for="id_permonant_address_pin">Permonant address pin:</label>
            <div class="col-sm-3">
             <input class="form-control"  id="id_permonant_address_pin" name="permonant_address_pin" type="number" />
            </div>
          </div>
          <div class="form-group">
            <label class="col-sm-2 control-label for="id_pan_no">Pan no:</label>
            <div class="col-sm-10">
             <input class="form-control"  id="id_pan_no" name="pan_no" type="text" />
            </div>
          </div>
          <div class="form-group">
            <label class="col-sm-2 control-label  for="id_passport_no">Passport no:</label>
            <div class="col-sm-10">
             <input class="form-control"  id="id_passport_no" name="passport_no" type="text" />
            </div>
          </div>
          <div class="form-group">
            <label class="col-sm-2 control-label for="id_mobile_no">Mobile no:</label>
            <div class="col-sm-10">
             <input class="form-control"  id="id_mobile_no" name="mobile_no" type="text" />
            </div>
          </div>
          <div class="form-group">
            <label class="col-sm-2 control-label for="id_landline_no">Landline no:</label>
            <div class="col-sm-10">
             <input class="form-control"  id="id_landline_no" name="landline_no" type="text" />
            </div>
          </div>
          <div class="form-group">
            <label class="col-sm-2 control-label for="id_e_mail">E mail:</label>
            <div class="col-sm-10">
             <input class="form-control"  id="id_e_mail" name="e_mail" type="email" />
            </div>
          </div>
          <div class="form-group">
            <label class="col-sm-2 control-label for="id_alternate_email">Alternate email:</label>
            <div class="col-sm-10">
             <input class="form-control"  id="id_alternate_email" name="alternate_email" type="email" />
            </div>
          </div>
          <div class="form-group">
            <label class="col-sm-2 control-label for="id_city">City:</label>
            <div class="col-sm-10">
             <input class="form-control"  id="id_city" name="city" type="text" />
            </div>
          </div>
          <div class="form-group">
            <label class="col-sm-2 control-label for="id_pin">Pin:</label>
            <div class="col-sm-3">
             <input class="form-control"  id="id_pin" name="pin" type="number" />
            </div>
          </div>
          <div class="form-group">
            <label class="col-sm-2 control-label for="id_state">State:</label>
            <div class="col-sm-10">
             <input class="form-control"  id="id_state" name="state" type="text" />
            </div>
          </div>
          <div class="form-group">
            <label class="col-sm-2 control-label for="id_country">Country:</label>
            <div class="col-sm-10">
             <input class="form-control"  id="id_country" name="country" type="text" />
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <div class="btn-group">
                  <input type="submit" class="btn btn-large btn-success" value="Submit" />
                  <input type="button" class="btn btn-large btn-warning" value="Clear" />
                  <input type="button" class="btn btn-large btn-success" value="Back" />
                </div>
            </div>
          </div>
        </form>
      </div>

      <hr>

      <div class="row-fluid marketing">
        <div class="span6">
          <h4>Subheading</h4>
          <p>Donec id elit non mi porta gravida at eget metus. Maecenas faucibus mollis interdum.</p>

          <h4>Subheading</h4>
          <p>Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Cras mattis consectetur purus sit amet fermentum.</p>

          <h4>Subheading</h4>
          <p>Maecenas sed diam eget risus varius blandit sit amet non magna.</p>
        </div>

        <div class="span6">
          <h4>Subheading</h4>
          <p>Donec id elit non mi porta gravida at eget metus. Maecenas faucibus mollis interdum.</p>

          <h4>Subheading</h4>
          <p>Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Cras mattis consectetur purus sit amet fermentum.</p>

          <h4>Subheading</h4>
          <p>Maecenas sed diam eget risus varius blandit sit amet non magna.</p>
        </div>
      </div>

      <hr>

      <div class="footer">
        <p>&copy; Company 2013</p>
      </div>

    </div> <!-- /container -->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static "bootstrap/js/jquery.js" %}"></script>
    <script src="{% static "bootstrap/js/bootstrap-transition.js" %}"></script>
    <script src="{% static "bootstrap/js/bootstrap-alert.js" %}"></script>
    <script src="{% static "bootstrap/js/bootstrap-modal.js" %}"></script>
    <script src="{% static "bootstrap/js/bootstrap-dropdown.js" %}"></script>
    <script src="{% static "bootstrap/js/bootstrap-scrollspy.js" %}"></script>
    <script src="{% static "bootstrap/js/bootstrap-tab.js" %}"></script>
    <script src="{% static "bootstrap/js/bootstrap-tooltip.js" %}"></script>
    <script src="{% static "bootstrap/js/bootstrap-popover.js" %}"></script>
    <script src="{% static "bootstrap/js/bootstrap-button.js" %}"></script>
    <script src="{% static "bootstrap/js/bootstrap-collapse.js" %}"></script>
    <script src="{% static "bootstrap/js/bootstrap-carousel.js" %}"></script>
    <script src="{% static "bootstrap/js/bootstrap-typeahead.js" %}"></script>
   </body>
</html>